//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarsiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FarsiLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FarsiLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("General.Language.FarsiLanguage", typeof(FarsiLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string _About {
            get {
                return ResourceManager.GetString("_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب بانکی.
        /// </summary>
        public static string _AcountNumber {
            get {
                return ResourceManager.GetString("_AcountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string _Address {
            get {
                return ResourceManager.GetString("_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه مدیریت.
        /// </summary>
        public static string _AdministratorPage {
            get {
                return ResourceManager.GetString("_AdministratorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافقت و امضا قرارداد بازاریابی.
        /// </summary>
        public static string _Agreement {
            get {
                return ResourceManager.GetString("_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش پورسانت پرداخت شده.
        /// </summary>
        public static string _AllWholeThingsPeymented {
            get {
                return ResourceManager.GetString("_AllWholeThingsPeymented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش پرداخت پورسانت .
        /// </summary>
        public static string _AllWholeThingsPeyments {
            get {
                return ResourceManager.GetString("_AllWholeThingsPeyments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ واریزی.
        /// </summary>
        public static string _AmountDeposit {
            get {
                return ResourceManager.GetString("_AmountDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیم و سقف درآمد.
        /// </summary>
        public static string _ArmAndIncome {
            get {
                return ResourceManager.GetString("_ArmAndIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تیم.
        /// </summary>
        public static string _ArmsNum {
            get {
                return ResourceManager.GetString("_ArmsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت.
        /// </summary>
        public static string _Back {
            get {
                return ResourceManager.GetString("_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات بانکی.
        /// </summary>
        public static string _BankStatus {
            get {
                return ResourceManager.GetString("_BankStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string _BirthCertificateId {
            get {
                return ResourceManager.GetString("_BirthCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه.
        /// </summary>
        public static string _BranchCode {
            get {
                return ResourceManager.GetString("_BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شعبه بانکی.
        /// </summary>
        public static string _BranchName {
            get {
                return ResourceManager.GetString("_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی.
        /// </summary>
        public static string _CardNumber {
            get {
                return ResourceManager.GetString("_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش زمانی درآمد.
        /// </summary>
        public static string _CashReportsOnPeriod {
            get {
                return ResourceManager.GetString("_CashReportsOnPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز ورود.
        /// </summary>
        public static string _ChangePass {
            get {
                return ResourceManager.GetString("_ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string _City {
            get {
                return ResourceManager.GetString("_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شهر.
        /// </summary>
        public static string _CityName {
            get {
                return ResourceManager.GetString("_CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد سود برای بازو.
        /// </summary>
        public static string _CommisionOnArms {
            get {
                return ResourceManager.GetString("_CommisionOnArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش پورسانت هر تیم.
        /// </summary>
        public static string _CommisionOnTeam {
            get {
                return ResourceManager.GetString("_CommisionOnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید پرداخت.
        /// </summary>
        public static string _ConfirmPayment {
            get {
                return ResourceManager.GetString("_ConfirmPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات تماس.
        /// </summary>
        public static string _ContactStatus {
            get {
                return ResourceManager.GetString("_ContactStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string _ContactsUs {
            get {
                return ResourceManager.GetString("_ContactsUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه.
        /// </summary>
        public static string _Continue {
            get {
                return ResourceManager.GetString("_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string _Create {
            get {
                return ResourceManager.GetString("_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف تیم.
        /// </summary>
        public static string _CreateArms {
            get {
                return ResourceManager.GetString("_CreateArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف تیم برای کاربران.
        /// </summary>
        public static string _CreateArmsForAll {
            get {
                return ResourceManager.GetString("_CreateArmsForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف تیم برای یوزر.
        /// </summary>
        public static string _CreateArmsForUser {
            get {
                return ResourceManager.GetString("_CreateArmsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف اقساط.
        /// </summary>
        public static string _CreateInstallment {
            get {
                return ResourceManager.GetString("_CreateInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم ایجاد سطح دسترسی جدید.
        /// </summary>
        public static string _CreateManageUserRolesForm {
            get {
                return ResourceManager.GetString("_CreateManageUserRolesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کاربر.
        /// </summary>
        public static string _CreateUsers {
            get {
                return ResourceManager.GetString("_CreateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم ایجاد کاربر جدید.
        /// </summary>
        public static string _CreateUsersForm {
            get {
                return ResourceManager.GetString("_CreateUsersForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string _DateofBirth {
            get {
                return ResourceManager.GetString("_DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پرداخت.
        /// </summary>
        public static string _DatePayment {
            get {
                return ResourceManager.GetString("_DatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string _Day {
            get {
                return ResourceManager.GetString("_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز پرداخت.
        /// </summary>
        public static string _DayDeposit {
            get {
                return ResourceManager.GetString("_DayDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز پرداخت.
        /// </summary>
        public static string _DayPayment {
            get {
                return ResourceManager.GetString("_DayPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string _Delete {
            get {
                return ResourceManager.GetString("_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات.
        /// </summary>
        public static string _Detail {
            get {
                return ResourceManager.GetString("_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع همکاری.
        /// </summary>
        public static string _DisconnectCooperation {
            get {
                return ResourceManager.GetString("_DisconnectCooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علت قطع همکاری.
        /// </summary>
        public static string _DisconnectCooperationCause {
            get {
                return ResourceManager.GetString("_DisconnectCooperationCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ قطع همکاری.
        /// </summary>
        public static string _DisconnectCooperationDate {
            get {
                return ResourceManager.GetString("_DisconnectCooperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کاربران غیرفعال.
        /// </summary>
        public static string _DisconnectedUser {
            get {
                return ResourceManager.GetString("_DisconnectedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string _Edit {
            get {
                return ResourceManager.GetString("_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرک.
        /// </summary>
        public static string _Education {
            get {
                return ResourceManager.GetString("_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد پست آموزشی.
        /// </summary>
        public static string _EducationalPamphletsCreate {
            get {
                return ResourceManager.GetString("_EducationalPamphletsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف پست آموزشی.
        /// </summary>
        public static string _EducationalPamphletsDelete {
            get {
                return ResourceManager.GetString("_EducationalPamphletsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات پست آموزشی.
        /// </summary>
        public static string _EducationalPamphletsDetail {
            get {
                return ResourceManager.GetString("_EducationalPamphletsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پست آموزشی.
        /// </summary>
        public static string _EducationalPamphletsEdit {
            get {
                return ResourceManager.GetString("_EducationalPamphletsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پست آموزشی.
        /// </summary>
        public static string _EducationalPamphletsList {
            get {
                return ResourceManager.GetString("_EducationalPamphletsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مدرک.
        /// </summary>
        public static string _EducationName {
            get {
                return ResourceManager.GetString("_EducationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string _FathersName {
            get {
                return ResourceManager.GetString("_FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        public static string _Female {
            get {
                return ResourceManager.GetString("_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالی.
        /// </summary>
        public static string _Finantial {
            get {
                return ResourceManager.GetString("_Finantial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string _FirstName {
            get {
                return ResourceManager.GetString("_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیم 1.
        /// </summary>
        public static string _FirstTeam {
            get {
                return ResourceManager.GetString("_FirstTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پیگیری.
        /// </summary>
        public static string _FolowUpNo {
            get {
                return ResourceManager.GetString("_FolowUpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بابت.
        /// </summary>
        public static string _For {
            get {
                return ResourceManager.GetString("_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور را فراموش کرده ام.
        /// </summary>
        public static string _ForgetPessword {
            get {
                return ResourceManager.GetString("_ForgetPessword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیم 4.
        /// </summary>
        public static string _ForthTeam {
            get {
                return ResourceManager.GetString("_ForthTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string _FullName {
            get {
                return ResourceManager.GetString("_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید اقساط پرداخت شده.
        /// </summary>
        public static string _InstallmenPaymentstAgreement {
            get {
                return ResourceManager.GetString("_InstallmenPaymentstAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقساط.
        /// </summary>
        public static string _Installment {
            get {
                return ResourceManager.GetString("_Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اقساط.
        /// </summary>
        public static string _InstallmentManagment {
            get {
                return ResourceManager.GetString("_InstallmentManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ قسط.
        /// </summary>
        public static string _InstallmentNumberAmount {
            get {
                return ResourceManager.GetString("_InstallmentNumberAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اقساط.
        /// </summary>
        public static string _InstallmentNumberNum {
            get {
                return ResourceManager.GetString("_InstallmentNumberNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسط های تایید نشده.
        /// </summary>
        public static string _InstallmentPaymentNotConfirm {
            get {
                return ResourceManager.GetString("_InstallmentPaymentNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش اقساط پرداخت شده با بازه زمانی.
        /// </summary>
        public static string _InstallmentPeriodReports {
            get {
                return ResourceManager.GetString("_InstallmentPeriodReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف اقساط.
        /// </summary>
        public static string _InstallmentsDifinition {
            get {
                return ResourceManager.GetString("_InstallmentsDifinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره بیمه نامه.
        /// </summary>
        public static string _InsuranceNumber {
            get {
                return ResourceManager.GetString("_InsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string _LastName {
            get {
                return ResourceManager.GetString("_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لایه.
        /// </summary>
        public static string _Layer {
            get {
                return ResourceManager.GetString("_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بازاریابی سرگروه.
        /// </summary>
        public static string _LeaderMarketingCode {
            get {
                return ResourceManager.GetString("_LeaderMarketingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح.
        /// </summary>
        public static string _Level {
            get {
                return ResourceManager.GetString("_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش وضعیت افراد بر اساس لایه.
        /// </summary>
        public static string _LevelPresonelArms {
            get {
                return ResourceManager.GetString("_LevelPresonelArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست.
        /// </summary>
        public static string _List {
            get {
                return ResourceManager.GetString("_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد لیست.
        /// </summary>
        public static string _ListCode {
            get {
                return ResourceManager.GetString("_ListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات مکانی.
        /// </summary>
        public static string _LocationStatus {
            get {
                return ResourceManager.GetString("_LocationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string _Login {
            get {
                return ResourceManager.GetString("_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به میز کار.
        /// </summary>
        public static string _LoginOnChairWork {
            get {
                return ResourceManager.GetString("_LoginOnChairWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه نخست.
        /// </summary>
        public static string _MainPage {
            get {
                return ResourceManager.GetString("_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string _Male {
            get {
                return ResourceManager.GetString("_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نقش های کاربر.
        /// </summary>
        public static string _ManageUserRoles {
            get {
                return ResourceManager.GetString("_ManageUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بازاریابی.
        /// </summary>
        public static string _MarketingCode {
            get {
                return ResourceManager.GetString("_MarketingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام ها و اطلاعیه ها.
        /// </summary>
        public static string _Messages {
            get {
                return ResourceManager.GetString("_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد پیام ها و اطلاعیه ها.
        /// </summary>
        public static string _MessagesCreate {
            get {
                return ResourceManager.GetString("_MessagesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف پیام ها و اطلاعیه ها.
        /// </summary>
        public static string _MessagesDelete {
            get {
                return ResourceManager.GetString("_MessagesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پیام ها و اطلاعیه ها.
        /// </summary>
        public static string _MessagesEdit {
            get {
                return ResourceManager.GetString("_MessagesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پیام ها و اطلاعیه ها.
        /// </summary>
        public static string _MessagesList {
            get {
                return ResourceManager.GetString("_MessagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        public static string _MobileNumber {
            get {
                return ResourceManager.GetString("_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه پرداخت.
        /// </summary>
        public static string _MonthDeposit {
            get {
                return ResourceManager.GetString("_MonthDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string _Mounth {
            get {
                return ResourceManager.GetString("_Mounth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه پرداخت.
        /// </summary>
        public static string _MounthPayment {
            get {
                return ResourceManager.GetString("_MounthPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش مجموع درآمد.
        /// </summary>
        public static string _MountlyCashReports {
            get {
                return ResourceManager.GetString("_MountlyCashReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نفر.
        /// </summary>
        public static string _Nafar {
            get {
                return ResourceManager.GetString("_Nafar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string _Name {
            get {
                return ResourceManager.GetString("_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string _NationalCode {
            get {
                return ResourceManager.GetString("_NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام جدید.
        /// </summary>
        public static string _NewRegister {
            get {
                return ResourceManager.GetString("_NewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره.
        /// </summary>
        public static string _Number {
            get {
                return ResourceManager.GetString("_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه ها.
        /// </summary>
        public static string _Options {
            get {
                return ResourceManager.GetString("_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string _Password {
            get {
                return ResourceManager.GetString("_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        public static string _Payment {
            get {
                return ResourceManager.GetString("_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش اقساط تایید شده.
        /// </summary>
        public static string _PaymentsConfirmReport {
            get {
                return ResourceManager.GetString("_PaymentsConfirmReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد سود.
        /// </summary>
        public static string _Percentage {
            get {
                return ResourceManager.GetString("_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت درصدها و متغیرها.
        /// </summary>
        public static string _PercentageAndVariablesManagment {
            get {
                return ResourceManager.GetString("_PercentageAndVariablesManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت درصدها.
        /// </summary>
        public static string _PercentageManage {
            get {
                return ResourceManager.GetString("_PercentageManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        public static string _Permition {
            get {
                return ResourceManager.GetString("_Permition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت حق دسترسی.
        /// </summary>
        public static string _PermitionManage {
            get {
                return ResourceManager.GetString("_PermitionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش افراد حاضر در تیم .
        /// </summary>
        public static string _PersonsInArms {
            get {
                return ResourceManager.GetString("_PersonsInArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات فردی.
        /// </summary>
        public static string _PersonStatus {
            get {
                return ResourceManager.GetString("_PersonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ثابت.
        /// </summary>
        public static string _Phone {
            get {
                return ResourceManager.GetString("_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین جایگاه.
        /// </summary>
        public static string _Position {
            get {
                return ResourceManager.GetString("_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string _PostalCode {
            get {
                return ResourceManager.GetString("_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بازاریابی معرف.
        /// </summary>
        public static string _RegentMK {
            get {
                return ResourceManager.GetString("_RegentMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string _Register {
            get {
                return ResourceManager.GetString("_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات.
        /// </summary>
        public static string _Reports {
            get {
                return ResourceManager.GetString("_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیم 2.
        /// </summary>
        public static string _SecondTeam {
            get {
                return ResourceManager.GetString("_SecondTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امنیت.
        /// </summary>
        public static string _Security {
            get {
                return ResourceManager.GetString("_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string _Send {
            get {
                return ResourceManager.GetString("_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پست های آموزشی.
        /// </summary>
        public static string _SendLearningPost {
            get {
                return ResourceManager.GetString("_SendLearningPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پاسخ.
        /// </summary>
        public static string _SendResponse {
            get {
                return ResourceManager.GetString("_SendResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string _Sex {
            get {
                return ResourceManager.GetString("_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        public static string _ShabaName {
            get {
                return ResourceManager.GetString("_ShabaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده اقساط.
        /// </summary>
        public static string _ShowInstallment {
            get {
                return ResourceManager.GetString("_ShowInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده سوالات.
        /// </summary>
        public static string _ShowQuestions {
            get {
                return ResourceManager.GetString("_ShowQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string _State {
            get {
                return ResourceManager.GetString("_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام استان.
        /// </summary>
        public static string _StateName {
            get {
                return ResourceManager.GetString("_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات.
        /// </summary>
        public static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاصل جمع.
        /// </summary>
        public static string _SumResult {
            get {
                return ResourceManager.GetString("_SumResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی.
        /// </summary>
        public static string _Support {
            get {
                return ResourceManager.GetString("_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع .
        /// </summary>
        public static string _SupportIssue {
            get {
                return ResourceManager.GetString("_SupportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیم 3.
        /// </summary>
        public static string _ThirdTeam {
            get {
                return ResourceManager.GetString("_ThirdTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اعضاء.
        /// </summary>
        public static string _UserMainPage {
            get {
                return ResourceManager.GetString("_UserMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string _UserName {
            get {
                return ResourceManager.GetString("_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش دسترسی ها.
        /// </summary>
        public static string _UserRolesList {
            get {
                return ResourceManager.GetString("_UserRolesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کاربران.
        /// </summary>
        public static string _UsersList {
            get {
                return ResourceManager.GetString("_UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string _UsersManagment {
            get {
                return ResourceManager.GetString("_UsersManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورژن.
        /// </summary>
        public static string _Version {
            get {
                return ResourceManager.GetString("_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string _Year {
            get {
                return ResourceManager.GetString("_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال پرداخت.
        /// </summary>
        public static string _YearDeposit {
            get {
                return ResourceManager.GetString("_YearDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال پرداخت.
        /// </summary>
        public static string _YearPayment {
            get {
                return ResourceManager.GetString("_YearPayment", resourceCulture);
            }
        }
    }
}
